// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBObQYwRivEYjqAmbtwEhFuFlfCWsAXrK4',
    appId: '1:889931011467:web:0c02d7f235128c2ebbcb8e',
    messagingSenderId: '889931011467',
    projectId: 'ghlindia',
    authDomain: 'ghlindia.firebaseapp.com',
    storageBucket: 'ghlindia.appspot.com',
    measurementId: 'G-3YLN4D6Q3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQVIRzQm2JPugRgC2U5v6fGg7jr2Z2vTQ',
    appId: '1:889931011467:android:bb7c495ba19a8949bbcb8e',
    messagingSenderId: '889931011467',
    projectId: 'ghlindia',
    storageBucket: 'ghlindia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByuYC5fiMLy0wsWlUATS-S4e-vPWvRvi0',
    appId: '1:889931011467:ios:72c113ac6d55c9c7bbcb8e',
    messagingSenderId: '889931011467',
    projectId: 'ghlindia',
    storageBucket: 'ghlindia.appspot.com',
    iosBundleId: 'com.example.ghlSalesCrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByuYC5fiMLy0wsWlUATS-S4e-vPWvRvi0',
    appId: '1:889931011467:ios:72c113ac6d55c9c7bbcb8e',
    messagingSenderId: '889931011467',
    projectId: 'ghlindia',
    storageBucket: 'ghlindia.appspot.com',
    iosBundleId: 'com.example.ghlSalesCrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBObQYwRivEYjqAmbtwEhFuFlfCWsAXrK4',
    appId: '1:889931011467:web:118d606c92da3705bbcb8e',
    messagingSenderId: '889931011467',
    projectId: 'ghlindia',
    authDomain: 'ghlindia.firebaseapp.com',
    storageBucket: 'ghlindia.appspot.com',
    measurementId: 'G-77KZ1W39PJ',
  );
}
